### ISSUE TITLE
Exception..

### ISSUE THREAD

**Issue by gayathri27selvam** [sashank/jsse#1]
i am getting "cipher not initialised" in the line 66 of stream cipher... y it s so? how to fix it?

**Comment by sashank** [comment]
Which file ?

**Comment by sashank** [comment]
Did you add bouncy castle dependency to your jars ?

**Comment by gayathri27selvam** [comment]
public static byte[] getRandomStreamOfBytes(long recordId, byte[] seedBytes) throws Exception {
        try {
            byte[] nonce = getNonce(recordId, seedBytes);
            cipher.init(Cipher.ENCRYPT_MODE, keySpec, new IvParameterSpec(nonce));
        }
        catch (Exception e){
            // do something later ;
        }

```
    // Plain text is 0 always we don't really care
    return cipher.doFinal(ByteBuffer.allocate(16).putInt(0).array());
}
```

am getting in " cipher.doFinal(ByteBuffer.allocate(16).putInt(0).array());". This is in StreamCipher.java.

**Comment by gayathri27selvam** [comment]
yeah.. i added....

**Comment by sashank** [comment]
Can you run , streamciphertest.java and see ? it is working fine for me now

**Comment by sashank** [comment]
is it working ?

**Comment by gayathri27selvam** [comment]
Sir,
It showing me like "Invalid ParametersNo such provider: BC" When i run
SWP.java file...

[image: Description: ink handwriting with feather pen on white background
Stock Photo - 4287958]
_gayathri_... :-)

**Comment by gayathri27selvam** [comment]
sir, am getting error in streamciphertest.java.... Its showing error in
"import org.bouncycastle.jce.provider.BouncyCastleProvider;"

[image: Description: ink handwriting with feather pen on white background
Stock Photo - 4287958]
_gayathri_... :-)

On Tue, Mar 10, 2015 at 7:45 PM, Gayathri Selvam <gayathrigayu2710@gmail.com

> wrote:
> 
> Sir,
> It showing me like "Invalid ParametersNo such provider: BC" When i run
> SWP.java file...
> 
> [image: Description: ink handwriting with feather pen on white background
> Stock Photo - 4287958]
> _gayathri_... :-)
>

**Comment by gayathri27selvam** [comment]
Now am using eclipse. added the bcprov-jdk15on-152.jar to the project. But
its not working.. showing the same error.

[image: Description: ink handwriting with feather pen on white background
Stock Photo - 4287958]
_gayathri_... :-)

On Tue, Mar 10, 2015 at 8:05 PM, Gayathri Selvam <gayathrigayu2710@gmail.com

> wrote:
> 
> sir, am getting error in streamciphertest.java.... Its showing error in
> "import org.bouncycastle.jce.provider.BouncyCastleProvider;"
> 
> [image: Description: ink handwriting with feather pen on white background
> Stock Photo - 4287958]
> _gayathri_... :-)
> 
> On Tue, Mar 10, 2015 at 7:45 PM, Gayathri Selvam <

**Comment by gayathri27selvam** [comment]
Sorry... i added wrong jar file previously... now added bcprov-1.45.jar...
now there is no error... but am getting output as "something went wrong
quitting"

[image: Description: ink handwriting with feather pen on white background
Stock Photo - 4287958]
_gayathri_... :-)

On Tue, Mar 10, 2015 at 8:13 PM, Gayathri Selvam <gayathrigayu2710@gmail.com

> wrote:
> 
> Now am using eclipse. added the bcprov-jdk15on-152.jar to the project. But
> its not working.. showing the same error.
> 
> [image: Description: ink handwriting with feather pen on white background
> Stock Photo - 4287958]
> _gayathri_... :-)
> 
> On Tue, Mar 10, 2015 at 8:05 PM, Gayathri Selvam <

**Comment by gayathri27selvam** [comment]
After running the AESTest.java... getting output as
"Test Randomized
Test Deterministic"

In SWPTest.java... getting output as
"Test AES Searchable
java.security.InvalidParameterException: Invalid ParametersJCE cannot
authenticate the provider BC"

[image: Description: ink handwriting with feather pen on white background
Stock Photo - 4287958]
_gayathri_... :-)

On Tue, Mar 10, 2015 at 8:26 PM, Gayathri Selvam <gayathrigayu2710@gmail.com

> wrote:
> 
> Sorry... i added wrong jar file previously... now added bcprov-1.45.jar...
> now there is no error... but am getting output as "something went wrong
> quitting"
> 
> [image: Description: ink handwriting with feather pen on white background
> Stock Photo - 4287958]
> _gayathri_... :-)
> 
> On Tue, Mar 10, 2015 at 8:13 PM, Gayathri Selvam <

**Comment by sashank** [comment]
I have double checked this , it is working fine for me .

**Comment by gayathri27selvam** [comment]
Am using java 8... after then i added "bcprov-jdk15on-1.51.jar" and changed
to unlimited strenght policies....

The output for

StreamcipherTest.java:
Same
Not Same

AESTest.java:
Test Randomized
Test Deterministic

SWPTest.java:
Test AES Searchable

Using only aes encryption.

Is this correct??

[image: Description: ink handwriting with feather pen on white background
Stock Photo - 4287958]
_gayathri_... :-)

**Comment by sashank** [comment]
That could be correct.  Can i ask what you are trying to do with this project ?

**Comment by gayathri27selvam** [comment]
Thanj you... :)
am doing a project on searchable encryption techniques.. thats why just
tried ur code...

[image: Description: ink handwriting with feather pen on white background
Stock Photo - 4287958]
_gayathri_... :-)
